// Generated from canonical JSON Schemas by scripts/contracts/generate-contract-types.mjs.
// JSON Schema remains runtime authority. Do not edit this file directly.

export type ActorRef = Readonly<{
  readonly actorId: string;
  readonly actorType: "HUMAN" | "AGENT" | "SYSTEM" | "WORKER";
  readonly actorVersion?: string;
  readonly displayName?: string;
}>;
export type ApplyWorkspaceChangePayload = Readonly<{
  readonly baseSnapshotHash: string;
  readonly desiredContentArtifactRef: ArtifactRef;
  readonly targetPath: string;
  readonly workspaceRef: string;
}>;
export type ApplyWorkspaceChangeResult = Readonly<{
  readonly afterSnapshotHash: string;
  readonly beforeSnapshotHash: string;
  readonly changeSetId: string;
  readonly changedPaths: readonly string[];
}>;
export type ArtifactRef = Readonly<{
  readonly artifactId: string;
  readonly logicalName?: string;
  readonly mediaType: string;
  readonly sensitivity: "PUBLIC" | "INTERNAL" | "CONFIDENTIAL" | "SECRET";
  readonly sha256: string;
  readonly sizeBytes: number;
}>;
export type CapabilityManifest = Readonly<{
  readonly capabilityId: string;
  readonly capabilityVersion: string;
  readonly isolationLevels: readonly (
    "PROCESS_RESTRICTED" | "OS_SANDBOXED" | "CONTAINER_ISOLATED" | "REMOTE_ISOLATED"
  )[];
  readonly operations: readonly string[];
  readonly permissionScopes: readonly string[];
  readonly riskClasses: readonly ("R0" | "R1" | "R2" | "R3" | "R4")[];
  readonly schemaVersion: "1.0.0";
}>;
export type CommandEnvelope = Readonly<{
  readonly actor: ActorRef;
  readonly aggregateId: string;
  readonly aggregateType: string;
  readonly causationId?: string;
  readonly commandId: string;
  readonly commandType: string;
  readonly correlationId: string;
  readonly expectedVersion: number;
  readonly idempotencyKey: string;
  readonly issuedAt: string;
  readonly payload: Readonly<Record<string, unknown>>;
  readonly payloadHash: string;
  readonly payloadSchema: SchemaRef;
  readonly requestId?: string;
  readonly schemaVersion: "1.0.0";
}>;
export type CreateWorkflowRunPayload = Readonly<{
  readonly inputArtifactRef: ArtifactRef;
  readonly workflowDefinitionId: string;
  readonly workflowDefinitionVersion: string;
}>;
export type DomainEventEnvelope = Readonly<{
  readonly actor: ActorRef;
  readonly aggregateId: string;
  readonly aggregateType: string;
  readonly aggregateVersion: number;
  readonly causationId: string;
  readonly correlationId: string;
  readonly eventId: string;
  readonly eventType: string;
  readonly occurredAt: string;
  readonly payload: Readonly<Record<string, unknown>>;
  readonly payloadHash: string;
  readonly payloadSchema: SchemaRef;
  readonly schemaVersion: "1.0.0";
}>;
export type EvidenceMetadata = Readonly<{
  readonly collectionMethod: string;
  readonly contentHash: string;
  readonly contentRef: ArtifactRef;
  readonly createdAt: string;
  readonly evidenceId: string;
  readonly evidenceType: string;
  readonly executionRef?: NodeExecutionIdentity;
  readonly mediaType: string;
  readonly producer: ActorRef;
  readonly producerVersion: string;
  readonly schemaVersion: "1.0.0";
  readonly sensitivity: "PUBLIC" | "INTERNAL" | "CONFIDENTIAL" | "SECRET";
  readonly subjectRefs: readonly SubjectRef[];
  readonly trustLevel:
    | "SYSTEM_AUTHORITY"
    | "SIGNED_POLICY"
    | "HUMAN_APPROVAL"
    | "VERIFIED_CONTRACT"
    | "TRUSTED_LOCAL_SOURCE"
    | "UNTRUSTED_CONTENT"
    | "MODEL_PROPOSAL";
}>;
export type FixtureChangeNodeContract = Readonly<{
  readonly allowedSideEffects: readonly ["write_workspace"];
  readonly contractId: "fixture-change-node";
  readonly inputSchemaRef: SchemaRef;
  readonly outputSchemaRef: SchemaRef;
  readonly verificationRequirements: readonly string[];
  readonly version: "1.0.0";
}>;
export type GateDecision = Readonly<{
  readonly assessmentRefs: readonly SubjectRef[];
  readonly decidedAt: string;
  readonly decisionId: string;
  readonly evaluatorVersion: string;
  readonly evidenceRefs: readonly SubjectRef[];
  readonly missingEvidence: readonly string[];
  readonly outcome:
    | "PASS"
    | "PASS_WITH_RISK_ACCEPTANCE"
    | "REWORK"
    | "BLOCK"
    | "REQUIRE_HUMAN_APPROVAL"
    | "FAIL_TERMINAL"
    | "INCONCLUSIVE";
  readonly planId: string;
  readonly policySnapshotId: string;
  readonly reasonCodes: readonly string[];
  readonly riskAcceptanceRefs: readonly SubjectRef[];
  readonly schemaVersion: "1.0.0";
  readonly subjectRef: SubjectRef;
}>;
export type NodeExecutionIdentity = Readonly<{
  readonly attempt: number;
  readonly executionId: string;
  readonly nodeId: string;
  readonly runId: string;
}>;
export type PolicyDecision = Readonly<{
  readonly decisionId: string;
  readonly evaluatedAt: string;
  readonly evaluatorVersion: string;
  readonly hardInvariantIds: readonly string[];
  readonly inputHash: string;
  readonly matchedRuleIds: readonly string[];
  readonly outcome: "ALLOW" | "ALLOW_WITH_REQUIREMENTS" | "DENY" | "INDETERMINATE";
  readonly policySnapshotHash: string;
  readonly policySnapshotId: string;
  readonly reasonCodes: readonly string[];
  readonly requirements: Readonly<{
    readonly approvalProfileRefs?: readonly SubjectRef[];
    readonly maxConcurrency?: number;
    readonly minimumIsolationLevel?:
      "PROCESS_RESTRICTED" | "OS_SANDBOXED" | "CONTAINER_ISOLATED" | "REMOTE_ISOLATED";
    readonly permissionScopes?: readonly string[];
    readonly postVerificationRequired?: boolean;
    readonly timeoutMs?: number;
    readonly verificationProfileRefs?: readonly SubjectRef[];
  }>;
  readonly residualRiskRefs: readonly SubjectRef[];
  readonly schemaVersion: "1.0.0";
}>;
export type PolicyEvaluationInput = Readonly<{
  readonly action: string;
  readonly authorityMutation: boolean;
  readonly capabilityIds: readonly string[];
  readonly capturedAt: string;
  readonly controlVerified: boolean;
  readonly dataClassification: "PUBLIC" | "INTERNAL" | "CONFIDENTIAL" | "SECRET";
  readonly direction: "LOCAL" | "INBOUND" | "OUTBOUND";
  readonly domain: string;
  readonly evaluationId: string;
  readonly permissionScopes: readonly string[];
  readonly policySnapshotId: string;
  readonly resourceType: string;
  readonly riskClass: "R0" | "R1" | "R2" | "R3" | "R4";
  readonly schemaVersion: "1.0.0";
  readonly subjectType: string;
}>;
export type PolicyRule = Readonly<{
  readonly action: string;
  readonly domain: string;
  readonly metadata: Readonly<Record<string, unknown>>;
  readonly reasonCode: string;
  readonly requirements: Readonly<{
    readonly maxConcurrency?: number;
    readonly minimumIsolationLevel?:
      "PROCESS_RESTRICTED" | "OS_SANDBOXED" | "CONTAINER_ISOLATED" | "REMOTE_ISOLATED";
    readonly permissionScopes?: readonly string[];
    readonly postVerificationRequired?: boolean;
    readonly timeoutMs?: number;
  }>;
  readonly resourceSelector: Readonly<{
    readonly resourceTypes: readonly string[];
  }>;
  readonly ruleEffect: "ALLOW" | "DENY";
  readonly ruleId: string;
  readonly schemaVersion: "1.0.0";
  readonly subjectSelector: Readonly<{
    readonly subjectTypes: readonly string[];
  }>;
  readonly when: Readonly<Record<string, unknown>>;
}>;
export type PolicySet = Readonly<{
  readonly constants: Readonly<Record<string, unknown>>;
  readonly defaultOutcome: "DENY";
  readonly description: string;
  readonly policySetId: string;
  readonly rules: readonly PolicyRule[];
  readonly schemaVersion: "1.0.0";
  readonly source: Readonly<{
    readonly kind: "RELEASE" | "MACHINE" | "USER" | "WORKSPACE" | "NODE" | "WORKFLOW";
    readonly ref: string;
  }>;
  readonly version: string;
}>;
export type PolicySnapshot = Readonly<{
  readonly compiledPolicySet: PolicySet;
  readonly compilerVersion: string;
  readonly createdAt: string;
  readonly policyHash: string;
  readonly policySetId: string;
  readonly policyVersion: string;
  readonly schemaVersion: "1.0.0";
  readonly snapshotId: string;
}>;
export type SchemaRef = Readonly<{
  readonly schemaHash: string;
  readonly schemaId: string;
  readonly schemaVersion: string;
}>;
export type SideEffectResultEnvelope = Readonly<{
  readonly adapterId: string;
  readonly adapterVersion: string;
  readonly attempt: number;
  readonly completedAt: string;
  readonly correlationId: string;
  readonly error?: TypedError;
  readonly evidenceRefs: readonly SubjectRef[];
  readonly executionId: string;
  readonly isolationEvidenceRef: ArtifactRef;
  readonly outcome:
    "SUCCEEDED" | "FAILED" | "CANCELLED" | "TIMED_OUT" | "UNKNOWN_REQUIRES_RECONCILIATION";
  readonly outputArtifactRefs: readonly ArtifactRef[];
  readonly payload: Readonly<Record<string, unknown>>;
  readonly payloadHash: string;
  readonly payloadSchema: SchemaRef;
  readonly resultId: string;
  readonly schemaVersion: "1.0.0";
  readonly selectedIsolationLevel:
    "PROCESS_RESTRICTED" | "OS_SANDBOXED" | "CONTAINER_ISOLATED" | "REMOTE_ISOLATED";
  readonly startedAt: string;
  readonly taskId: string;
}>;
export type SideEffectTaskEnvelope = Readonly<{
  readonly adapterContractVersion: string;
  readonly attempt: number;
  readonly capability: string;
  readonly causationId?: string;
  readonly correlationId: string;
  readonly effectScope: string;
  readonly executionId: string;
  readonly idempotencyKey: string;
  readonly inputArtifactRefs: readonly ArtifactRef[];
  readonly payload: Readonly<Record<string, unknown>>;
  readonly payloadHash: string;
  readonly payloadSchema: SchemaRef;
  readonly permissionSet: readonly string[];
  readonly requiredIsolationLevel:
    "PROCESS_RESTRICTED" | "OS_SANDBOXED" | "CONTAINER_ISOLATED" | "REMOTE_ISOLATED";
  readonly resourceBudget: Readonly<{
    readonly maxCpuTimeMs?: number;
    readonly maxMemoryBytes: number;
    readonly maxOutputBytes: number;
    readonly maxProcessCount: number;
    readonly networkMode?: "DENY" | "ALLOWLIST";
  }>;
  readonly schemaVersion: "1.0.0";
  readonly taskId: string;
  readonly timeoutMs: number;
}>;
export type SubjectRef = Readonly<{
  readonly subjectId: string;
  readonly subjectType: string;
  readonly subjectVersion?: string;
}>;
export type TypedError = Readonly<{
  readonly category:
    | "VALIDATION"
    | "CONFLICT"
    | "POLICY"
    | "AUTHENTICATION"
    | "AUTHORIZATION"
    | "UNAVAILABLE"
    | "TIMEOUT"
    | "CANCELLED"
    | "INFRASTRUCTURE"
    | "INVARIANT"
    | "SECURITY"
    | "RECONCILIATION";
  readonly causationId?: string;
  readonly code: string;
  readonly details?: Readonly<Record<string, unknown>>;
  readonly message: string;
  readonly remediation?: string;
  readonly retryability: "RETRYABLE" | "NON_RETRYABLE" | "CONDITIONAL" | "UNKNOWN";
  readonly subjectRef?: SubjectRef;
}>;
export type VerificationPlan = Readonly<{
  readonly contractRefs: readonly SchemaRef[];
  readonly createdAt: string;
  readonly planId: string;
  readonly plannerId: string;
  readonly plannerVersion: string;
  readonly policySnapshotId: string;
  readonly riskClass: "R0" | "R1" | "R2" | "R3" | "R4";
  readonly risksCovered: readonly string[];
  readonly risksNotCovered: readonly string[];
  readonly schemaVersion: "1.0.0";
  readonly steps: readonly Readonly<{
    readonly dependsOn: readonly string[];
    readonly executorCapability: string;
    readonly expectedEvidenceTypes: readonly string[];
    readonly inputRefs: readonly SubjectRef[];
    readonly kind:
      | "SCHEMA"
      | "STATIC"
      | "COMPILE"
      | "UNIT"
      | "CONTRACT"
      | "INTEGRATION"
      | "STARTUP_HEALTH"
      | "E2E"
      | "ORACLE"
      | "PROPERTY"
      | "MUTATION"
      | "FUZZ"
      | "ARCHITECTURE"
      | "SECURITY"
      | "REPLAY"
      | "MIGRATION"
      | "ROLLBACK"
      | "HUMAN_REVIEW";
    readonly required: boolean;
    readonly retryPolicy: Readonly<{
      readonly maxAttempts: number;
      readonly retryableErrorCodes: readonly string[];
    }>;
    readonly stepId: string;
    readonly timeoutMs: number;
  }>[];
  readonly subjectRef: SubjectRef;
}>;
export type WorkflowRunCreatedPayload = Readonly<{
  readonly createdByCommandId: string;
  readonly workflowDefinitionId: string;
  readonly workflowDefinitionVersion: string;
}>;
